[package]
name = "sui_on_aptos"
version = "0.0.1"

[addresses]
sui_on_aptos = "7fb9d233fce09d16df966695362cdafa102e355c6f05c2b4cab4dda9cf8d9084"

[dependencies.AptosFramework]
git = 'https://github.com/shaokun11/move-me2'
rev = '4bbd43f73a621cdf2da37c14c345ed6281c2b7ab'
subdir = 'aptos-move/framework/aptos-framework'