export const vmErrors = {
    10001: 'vm error addr length',
    10002: 'vm error params length',
    51: 'static state change',
    53: 'invalid opcode',
    55: 'exceed initcode size',
    56: 'invalid return data copy size',
    57: 'create contract collision',
    58: 'invalid pc',
    59: 'pop stack',
    60: 'invalid chainid',
    200: 'success',
    201: '1559 max fee lower than base fee',
    202: 'legacy gas price lower than base fee',
    203: 'gas limit exceed block limit',
    204: 'create contract code size exceed',
    205: 'insufficient balance to send tx',
    206: 'sender not eoa',
    207: 'out of gas',
    208: 'execution reverted',
    1024: 'max stack size',
    49152: 'max init code size',
    24576: 'max code size',
};
