[package]
name = "batch_transfer"
version = "1.0.0"
authors = []

[addresses]
batch_transfer = "0x1"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dev-dependencies]
